[unix_http_server]
file=/run/supervisord.sock

[supervisord]
logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10           ; (num of main logfile rotation backups;default 10)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=false               ; (start in foreground if true;default false)
minfds=1024                  ; (min. avail startup file descriptors;default 1024)
minprocs=200                 ; (min. avail process descriptors;default 200)
user=root                    ; (default is current user, required if root)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize --fpm-config=/usr/local/etc/php-fpm.d/www.conf -c /usr/local/etc/php/php.ini
priority=1
startretries=5
autorestart=true
stdout_events_enabled=true
stderr_events_enabled=true
stderr_logfile=/tmp/php-fpm-err.log
stdout_logfile=/tmp/php-fpm.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=2
startretries=3
autorestart=true
stdout_events_enabled=true
stderr_events_enabled=true
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:laravel-queue]
command=php /app/artisan queue:work --tries=3 --timeout=320
directory=/app
process_name=%(program_name)s_%(process_num)02d
numprocs=2
priority=3
autostart=true
autorestart=true
startsecs=1
startretries=3
stdout_events_enabled=true
stderr_events_enabled=true
stderr_logfile=/tmp/queue-err.log
stdout_logfile=/tmp/queue.log

[include]
files = /etc/supervisor.d/*.ini
