user nginx;

worker_processes auto;

pcre_jit on;

error_log  /dev/stdout  warn;

include /etc/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server_tokens off;

    keepalive_timeout  65;

    client_max_body_size 1G;

    sendfile on;
    tcp_nopush on;

    gzip_vary on;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    log_format main 'time="$time_iso8601" status_code="$status" '
        'http_referer="$http_referer" http_user_agent="$http_user_agent" '
        'dest_port="$server_port" dest_ip="$server_addr" '
        'src="$remote_addr" src_ip="$realip_remote_addr" user="$remote_user" '
        'method="$request_method" request="$request_body " '
        'request_time="${request_time}ms" response_time="${upstream_response_time}ms" url="$request"';

    access_log  /dev/stdout  main;

    include /etc/nginx/http.d/*.conf;
}
